on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run build
      
      - run: |
          git config --global user.email "davlago@ucm.es"
          git config --global user.name "davlago"
          git remote set-url origin https://{username}:{password}@github.com/{username}/project.git
          npm run deploy
          
        env:
          github_token: ${{ secrets.DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
