on: push
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - run: node --version
      - run: npm --version
      - uses: actions/checkout@v3
      - run: npm install
      - name: Build and Deploy
        run: |
          git config --global user.name "user_name"
          git config --global user.email"user_email@mail.com"
          npm run deploy
      - name: Init
        run: npm start
